# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cf692c5d23284d93c064cb5e5126e1a8495357c5ffd1b2bacaffeeb07e1175290e3afe2e6cfa1d17aa2d8a57e4cbdfe911f6ec0f4928f789046848bcedb225a

test:
  secret_key_base: 841d560488303afd1a39d563f4082f24f00ba734362244cef38a6cdbbddce5b90ee19489a68abe83dd5c1d9534cf92af4fe68e150215340ec0ebc949e07aa964

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
